"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
const API_BASE=process.env.NEXT_PUBLIC_API_BASE_URL;
interface Session{id:number;name:string;is_active:boolean} interface ClassRoom{id:number;name:string;academic_session_id:number}
interface Component{id?:number;name:string;amount:string;description:string}
interface Structure{id:number;name:string;description:string;total_amount:string;due_date:string|null;is_active:boolean;academic_session:{id:number};class_room:{id:number};components:Component[]}
export default function FeeStructureForm({structureId}:{structureId?:string}){
 const router=useRouter(),[sessions,setSessions]=useState<Session[]>([]),[classes,setClasses]=useState<ClassRoom[]>([]),[name,setName]=useState(""),[description,setDescription]=useState(""),[sessionId,setSessionId]=useState(""),[classId,setClassId]=useState(""),[dueDate,setDueDate]=useState(""),[active,setActive]=useState(true),[components,setComponents]=useState<Component[]>([{name:"",amount:"",description:""}]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const token=useCallback(()=>{const t=localStorage.getItem("college_admin_access_token");if(!t)router.replace("/college-admin/login");return t},[router]);
 useEffect(()=>{let mounted=true;(async()=>{const t=token();if(!t)return;try{const setup=await fetch(`${API_BASE}/api/fees/college-admin/setup/`,{headers:{Authorization:`Bearer ${t}`}});const sj=await setup.json();if(!setup.ok)throw new Error(sj.detail||"Unable to load fee setup.");if(mounted){setSessions(sj.academic_sessions||[]);setClasses(sj.classes||[])}
 if(structureId){const r=await fetch(`${API_BASE}/api/fees/college-admin/structures/${structureId}/`,{headers:{Authorization:`Bearer ${t}`}});const j=await r.json();if(!r.ok)throw new Error(j.detail||"Unable to load fee structure.");const x=j.structure as Structure;if(mounted){setName(x.name);setDescription(x.description||"");setSessionId(String(x.academic_session.id));setClassId(String(x.class_room.id));setDueDate(x.due_date||"");setActive(x.is_active);setComponents(x.components.map(c=>({name:c.name,amount:String(c.amount),description:c.description||""})))}}}catch(e){if(mounted)setError(e instanceof Error?e.message:"Unable to load form.")}finally{if(mounted)setLoading(false)}})();return()=>{mounted=false}},[structureId,token]);
 const available=useMemo(()=>classes.filter(c=>!sessionId||String(c.academic_session_id)===sessionId),[classes,sessionId]);
 const total=useMemo(()=>components.reduce((s,c)=>s+(Number(c.amount)||0),0),[components]);
 const change=(i:number,key:keyof Component,value:string)=>setComponents(v=>v.map((c,n)=>n===i?{...c,[key]:value}:c));
 const submit=async(e:FormEvent)=>{e.preventDefault();const t=token();if(!t)return;setSaving(true);setError("");try{const url=structureId?`${API_BASE}/api/fees/college-admin/structures/${structureId}/`:`${API_BASE}/api/fees/college-admin/structures/`;const r=await fetch(url,{method:structureId?"PATCH":"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${t}`},body:JSON.stringify({name,description,academic_session_id:Number(sessionId),class_room_id:Number(classId),total_amount:total.toFixed(2),due_date:dueDate||null,is_active:active,components:components.map(c=>({...c,amount:Number(c.amount||0).toFixed(2)}))})});const j=await r.json();if(!r.ok){const msg=j.detail||j.components||j.total_amount||"Unable to save fee structure.";throw new Error(Array.isArray(msg)?msg.join(", "):String(msg))}router.replace("/college-admin/fees/structures")}catch(e){setError(e instanceof Error?e.message:"Unable to save fee structure.")}finally{setSaving(false)}};
 if(loading)return <div className="card border-0 shadow-sm"><div className="card-body py-5 text-center text-muted">Loading fee structure...</div></div>;
 return <>{error&&<div className="alert alert-danger">{error}</div>}<div className="card border-0 shadow-sm"><div className="card-body p-4"><form onSubmit={submit}><div className="row g-3">
 <div className="col-md-6"><label className="form-label">Structure Name</label><input className="form-control" value={name} onChange={e=>setName(e.target.value)} required placeholder="e.g. Digital Marketing 2026-27 Fee"/></div>
 <div className="col-md-3"><label className="form-label">Academic Session</label><select className="form-select" value={sessionId} onChange={e=>{setSessionId(e.target.value);setClassId("")}} required><option value="">Select session</option>{sessions.map(x=><option key={x.id} value={x.id}>{x.name}{x.is_active?" (Active)":""}</option>)}</select></div>
 <div className="col-md-3"><label className="form-label">Class</label><select className="form-select" value={classId} onChange={e=>setClassId(e.target.value)} required><option value="">Select class</option>{available.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div>
 <div className="col-md-8"><label className="form-label">Description</label><input className="form-control" value={description} onChange={e=>setDescription(e.target.value)}/></div><div className="col-md-4"><label className="form-label">Due Date</label><input type="date" className="form-control" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></div>
 <div className="col-12"><div className="d-flex justify-content-between align-items-center mb-2"><h5 className="mb-0">Fee Components</h5><button type="button" className="btn btn-outline-primary btn-sm" onClick={()=>setComponents(v=>[...v,{name:"",amount:"",description:""}])}>Add Component</button></div>
 {components.map((c,i)=><div className="row g-2 mb-2" key={i}><div className="col-md-4"><input className="form-control" placeholder="Component name" value={c.name} onChange={e=>change(i,"name",e.target.value)} required/></div><div className="col-md-3"><input className="form-control" type="number" min="0" step="0.01" placeholder="Amount" value={c.amount} onChange={e=>change(i,"amount",e.target.value)} required/></div><div className="col-md-4"><input className="form-control" placeholder="Description (optional)" value={c.description} onChange={e=>change(i,"description",e.target.value)}/></div><div className="col-md-1 d-grid"><button type="button" className="btn btn-outline-danger" disabled={components.length===1} onClick={()=>setComponents(v=>v.filter((_,n)=>n!==i))}>×</button></div></div>)}
 <div className="text-end fw-bold mt-2">Total: ₹{total.toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}</div></div>
 <div className="col-12"><div className="form-check"><input id="fee-active" className="form-check-input" type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/><label htmlFor="fee-active" className="form-check-label">Active fee structure</label></div></div>
 <div className="col-12 d-flex gap-2"><button className="btn btn-primary" disabled={saving}>{saving?"Saving...":structureId?"Save Changes":"Create Fee Structure"}</button><button type="button" className="btn btn-outline-secondary" onClick={()=>router.push("/college-admin/fees/structures")}>Cancel</button></div>
 </div></form></div></div></>
}