"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import CollegeAdminSidebar from "@/components/college-admin/CollegeAdminSidebar";
import CollegeAdminTopbar from "@/components/college-admin/CollegeAdminTopbar";
import "../../teacher/dashboard/dashboard.css";

const API_BASE=process.env.NEXT_PUBLIC_API_BASE_URL;
type Purchase={id:number;course:{id:number;title:string};student:{id:number;name:string;admission_number:string};buyer_type:string;amount:string;status:string;payment_method:string;payment_reference:string;paid_at:string|null;created_at:string};

export default function RecordedCoursePurchasesPage(){
 const router=useRouter();const [admin]=useState<any>(()=>{try{return JSON.parse(localStorage.getItem("college_admin_user")||"{}")}catch{return {}}});const [items,setItems]=useState<Purchase[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [verifyId,setVerifyId]=useState<number|null>(null);const [method,setMethod]=useState("cash");const [reference,setReference]=useState("");const [busy,setBusy]=useState(false);
 const money=(v:string)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(Number(v));
 const load=useCallback(async()=>{const token=localStorage.getItem("college_admin_access_token");if(!token){router.replace("/college-admin/login");return}setLoading(true);setError("");try{const r=await fetch(API_BASE+"/api/recorded-courses/college-admin/purchases/",{headers:{Authorization:"Bearer "+token}});const j=await r.json();if(!r.ok)throw new Error(j.detail||"Unable to load purchases.");setItems(j.purchases||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load purchases.")}finally{setLoading(false)}},[router]);
 useEffect(()=>{void load()},[load]);
 async function verify(e:FormEvent){e.preventDefault();if(!verifyId)return;const token=localStorage.getItem("college_admin_access_token");if(!token)return;setBusy(true);setError("");try{const r=await fetch(API_BASE+"/api/recorded-courses/college-admin/purchases/"+verifyId+"/verify/",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({payment_method:method,payment_reference:reference})});const j=await r.json();if(!r.ok)throw new Error(j.detail||j.payment_method||"Unable to verify payment.");setVerifyId(null);setReference("");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to verify payment.")}finally{setBusy(false)}}
 const pending=items.filter(x=>x.status==="pending").length;
 return <div className="teacher-dashboard"><CollegeAdminSidebar/><main className="teacher-dashboard-main"><CollegeAdminTopbar name={admin.name||admin.username||"College Admin"} organization={admin.organization||""}/><div className="teacher-dashboard-content"><div className="container-fluid">
 <div className="d-flex justify-content-between align-items-start flex-wrap gap-3 mb-4"><div><h2 className="fw-bold mb-1">Recorded Course Purchases</h2><p className="text-muted mb-0">Verify offline payments before granting course access.</p></div><span className="badge bg-warning text-dark fs-6">{pending} Pending</span></div>{error&&<div className="alert alert-danger">{error}</div>}
 <div className="card border-0 shadow-sm"><div className="table-responsive">{loading?<div className="p-5 text-center text-muted">Loading purchases...</div>:items.length===0?<div className="p-5 text-center text-muted">No recorded course purchases yet.</div>:<table className="table align-middle mb-0"><thead><tr><th>Student</th><th>Course</th><th>Buyer</th><th>Amount</th><th>Created</th><th>Status</th><th>Action</th></tr></thead><tbody>{items.map(p=><tr key={p.id}><td><div className="fw-semibold">{p.student.name}</div><small className="text-muted">{p.student.admission_number||"-"}</small></td><td>{p.course.title}</td><td className="text-capitalize">{p.buyer_type}</td><td>{money(p.amount)}</td><td>{new Date(p.created_at).toLocaleDateString()}</td><td><span className={"badge "+(p.status==="paid"?"bg-success":p.status==="pending"?"bg-warning text-dark":"bg-secondary")}>{p.status.toUpperCase()}</span></td><td>{p.status==="pending"?<button className="btn btn-sm btn-primary" onClick={()=>{setVerifyId(p.id);setMethod("cash");setReference("")}}>Verify Payment</button>:<div><small>{p.payment_method||"Verified"}</small>{p.payment_reference&&<div className="text-muted small">{p.payment_reference}</div>}</div>}</td></tr>)}</tbody></table>}</div></div>
 {verifyId!==null&&<div className="card border-0 shadow-sm mt-4"><div className="card-body"><h5 className="fw-bold mb-3">Verify Payment — Purchase #{verifyId}</h5><div className="alert alert-warning">Confirm that payment has actually been received before verifying. Verification immediately grants the student course access.</div><form onSubmit={verify}><div className="row g-3"><div className="col-md-4"><label className="form-label">Payment Method</label><select className="form-select" value={method} onChange={e=>setMethod(e.target.value)} required><option value="cash">Cash</option><option value="bank_transfer">Bank Transfer</option><option value="upi">UPI</option><option value="card">Card</option><option value="other">Other</option></select></div><div className="col-md-5"><label className="form-label">Payment Reference</label><input className="form-control" value={reference} onChange={e=>setReference(e.target.value)} placeholder="Receipt / UTR / transaction reference"/></div><div className="col-md-3 d-flex align-items-end gap-2"><button className="btn btn-success" disabled={busy}>{busy?"Verifying...":"Confirm & Grant Access"}</button><button type="button" className="btn btn-outline-secondary" disabled={busy} onClick={()=>setVerifyId(null)}>Cancel</button></div></div></form></div></div>}
 </div></div></main></div>
}