"use client";
import {useCallback,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import ParentSidebar from "@/components/parent/ParentSidebar";
import ParentTopbar from "@/components/parent/ParentTopbar";
import { useCurrency } from "@/hooks/useCurrency";
import "../../student/dashboard/dashboard.css";
const API_BASE=process.env.NEXT_PUBLIC_API_BASE_URL;
export default function ParentRecordedCoursesPage(){
 const router=useRouter();const [parent,setParent]=useState<any>({});const [children,setChildren]=useState<any[]>([]);const [selected,setSelected]=useState("");const [courses,setCourses]=useState<any[]>([]);const [purchases,setPurchases]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [busy,setBusy]=useState<number|null>(null);const { formatCurrency: money } = useCurrency();
 const load=useCallback(async()=>{const token=localStorage.getItem("parent_access_token");if(!token){router.replace("/parent/login");return}setLoading(true);try{const h={Authorization:"Bearer "+token};const [cr,pr]=await Promise.all([fetch(API_BASE+"/api/recorded-courses/parent/catalog/",{headers:h}),fetch(API_BASE+"/api/recorded-courses/parent/purchases/",{headers:h})]);const cj=await cr.json(),pj=await pr.json();if(!cr.ok)throw new Error(cj.detail||"Unable to load courses.");if(!pr.ok)throw new Error(pj.detail||"Unable to load purchases.");setChildren(cj.children||[]);setSelected(s=>s||String(cj.children?.[0]?.id||""));setCourses(cj.courses||[]);setPurchases(pj.purchases||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load courses.")}finally{setLoading(false)}},[router]);
 useEffect(()=>{try{setParent(JSON.parse(localStorage.getItem("parent_user")||"{}"))}catch{};void load()},[load]);
 const selectedChild=children.find(c=>String(c.id)===selected);
 const parentCourseAccess=selectedChild?.parent_feature_enabled!==false;
 const pending=(cid:number)=>purchases.find(p=>p.course.id===cid&&String(p.student.id)===selected&&p.status==="pending");
 async function purchase(cid:number){if(!selected)return;const token=localStorage.getItem("parent_access_token");if(!token)return;setBusy(cid);setError("");try{const r=await fetch(API_BASE+"/api/recorded-courses/parent/purchases/",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({course_id:cid,student_id:Number(selected)})});const j=await r.json();if(!r.ok)throw new Error(j.detail||"Unable to create purchase.");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to create purchase.")}finally{setBusy(null)}}
 return <div className="student-dashboard"><ParentSidebar/><main className="student-dashboard-main"><ParentTopbar name={parent.name||parent.username||"Parent"} organization={parent.organization||""}/><div className="student-dashboard-content"><div className="container-fluid">
 <div className="mb-4"><h2 className="fw-bold">Recorded Courses</h2><p className="text-muted">Purchase a recorded course for a linked child.</p></div>{error&&<div className="alert alert-danger">{error}</div>}
 <div className="dashboard-panel mb-4"><div className="col-md-6"><label className="form-label fw-semibold">Purchase For</label><select className="form-select" value={selected} onChange={e=>setSelected(e.target.value)} disabled={!children.length}>{!children.length&&<option value="">No linked children</option>}{children.map(c=><option value={c.id} key={c.id}>{c.name}{c.admission_number?" - "+c.admission_number:""}</option>)}</select></div>{selected&&!parentCourseAccess&&<div className="alert alert-warning mt-3 mb-0">Recorded Courses have been restricted for parents of this child&apos;s class.</div>}</div>
 {loading?<div className="dashboard-panel"><div className="empty-state">Loading...</div></div>:<div className="row g-4">{courses.map(c=><div className="col-md-6 col-xl-4" key={c.id}><div className="card border-0 shadow-sm h-100"><div className="card-body d-flex flex-column"><h5 className="fw-bold">{c.title}</h5><p className="text-muted flex-grow-1">{c.description||"Recorded course"}</p><div>Lessons: <strong>{c.lesson_count}</strong></div><div>Access: <strong>{c.access_duration_days} days</strong></div><div className="fs-4 fw-bold my-3">{money(c.price)}</div>{pending(c.id)?<div className="alert alert-warning py-2 mb-0">Purchase Pending Verification</div>:<button className="btn btn-primary" disabled={!selected||!parentCourseAccess||busy===c.id} onClick={()=>purchase(c.id)}>{busy===c.id?"Processing...":"Purchase for Child"}</button>}</div></div></div>)}</div>}
 {purchases.length>0&&<div className="dashboard-panel mt-4"><div className="panel-heading"><h5>Purchase History</h5></div><div className="table-responsive"><table className="table mb-0"><thead><tr><th>Child</th><th>Course</th><th>Amount</th><th>Status</th></tr></thead><tbody>{purchases.map(p=><tr key={p.id}><td>{p.student.name}</td><td>{p.course.title}</td><td>{money(p.amount)}</td><td>{p.status.toUpperCase()}</td></tr>)}</tbody></table></div></div>}
 </div></div></main></div>
}