# Generated by Django 5.2.17 on 2026-09-02 05:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_organization_alter_user_role'),
        ('liveclasses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClassRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='recorded_classes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov'])])),
                ('title', models.CharField(blank=True, max_length=150)),
                ('is_available', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('live_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='liveclasses.liveclass')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_recordings', to='accounts.teacherprofile')),
            ],
        ),
    ]
