# Generated by Django 5.2.17 on 2026-09-02 07:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclasses', '0002_liveclassrecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclassrecording',
            name='public_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
