# Generated by Django 5.2.17 on 2026-09-02 07:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclasses', '0003_liveclassrecording_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclassrecording',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
