# Generated by Django 5.2.17 on 2026-09-02 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclasses', '0006_alter_liveclassrecording_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclassrecording',
            name='video',
            field=models.FileField(upload_to='recorded_classes/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov'])]),
        ),
    ]
