# Generated by Django 5.2.17 on 2026-09-02 09:18

import django.core.files.storage
import django.core.validators
import liveclasses.models
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclasses', '0008_alter_liveclassrecording_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclassrecording',
            name='video',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/student_LMS/private_media')), upload_to=liveclasses.models.live_class_recording_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov'])]),
        ),
    ]
