# Generated by Django 5.2.17 on 2026-09-14 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_organiz_c8c476_idx',
            old_name='documents_d_organiz_84fef0_idx',
        ),
        migrations.RenameIndex(
            model_name='document',
            new_name='documents_d_teacher_aadfd3_idx',
            old_name='documents_d_teacher_c7f338_idx',
        ),
    ]
