# Generated by Django 5.2.17 on 2026-08-29 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_parentstudent_studentenrollment_teacherassignment'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_sessions', to='institutions.organization'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='institutions.organization'),
        ),
        migrations.AddField(
            model_name='section',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='institutions.organization'),
        ),
        migrations.AddField(
            model_name='subject',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='institutions.organization'),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='academicsession',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('organization', 'name', 'academic_session')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('organization', 'name', 'classroom')},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('organization', 'name', 'classroom')},
        ),
    ]
