# Generated by Django 5.2.17 on 2026-09-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_classroom_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsession',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Session Name'),
        ),
    ]
