# Generated by Django 5.2.17 on 2026-09-14 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_427e4b_idx',
            old_name='notificatio_user_id_5a8c6c_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_organiz_3a1f89_idx',
            old_name='notificatio_organiz_f91b48_idx',
        ),
    ]
