"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import CollegeAdminSidebar from "@/components/college-admin/CollegeAdminSidebar";
import CollegeAdminTopbar from "@/components/college-admin/CollegeAdminTopbar";
import "../../../teacher/dashboard/dashboard.css";

const API_BASE=process.env.NEXT_PUBLIC_API_BASE_URL;
export default function RecordedCourseManagePage(){
 const {id}=useParams<{id:string}>();const router=useRouter();const [course,setCourse]=useState<any>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(true);
 const [lesson,setLesson]=useState({title:"",description:"",position:"1",video:null as File|null});
 const [admin]=useState<any>(()=>{try{return JSON.parse(localStorage.getItem("college_admin_user")||"{}")}catch{return {}}});
 const load=useCallback(async()=>{const token=localStorage.getItem("college_admin_access_token");if(!token){router.replace("/college-admin/login");return}setLoading(true);try{const r=await fetch(`${API_BASE}/api/recorded-courses/college-admin/courses/${id}/`,{headers:{Authorization:`Bearer ${token}`}});const j=await r.json();if(!r.ok)throw new Error(j.detail||"Unable to load course.");setCourse(j.course)}catch(e){setError(e instanceof Error?e.message:"Unable to load course.")}finally{setLoading(false)}},[id,router]);
 useEffect(()=>{void load()},[load]);
 async function update(e:FormEvent){e.preventDefault();const token=localStorage.getItem("college_admin_access_token");if(!token)return;const r=await fetch(`${API_BASE}/api/recorded-courses/college-admin/courses/${id}/`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({title:course.title,description:course.description,price:course.price,access_duration_days:Number(course.access_duration_days),is_active:course.is_active})});const j=await r.json();if(!r.ok){setError(j.detail||Object.values(j).join(", "));return}setCourse({...course,...j.course});}
 async function upload(e:FormEvent){e.preventDefault();if(!lesson.video)return;const token=localStorage.getItem("college_admin_access_token");if(!token)return;const fd=new FormData();fd.append("title",lesson.title);fd.append("description",lesson.description);fd.append("position",lesson.position);fd.append("video",lesson.video);const r=await fetch(`${API_BASE}/api/recorded-courses/college-admin/courses/${id}/lessons/`,{method:"POST",headers:{Authorization:`Bearer ${token}`},body:fd});const j=await r.json();if(!r.ok){setError(j.detail||Object.values(j).join(", "));return}setLesson({title:"",description:"",position:String((course.lessons?.length||0)+2),video:null});await load();}
 if(loading)return <div className="p-5 text-center">Loading recorded course...</div>;if(!course)return <div className="p-5 text-danger">{error||"Course not found."}</div>;
 return <div className="teacher-dashboard"><CollegeAdminSidebar/><main className="teacher-dashboard-main"><CollegeAdminTopbar name={admin.name||admin.username||"College Admin"} organization={admin.organization||""}/><div className="teacher-dashboard-content"><div className="container-fluid">
 <div className="mb-4"><button className="btn btn-link px-0" onClick={()=>router.push("/college-admin/recorded-courses")}>← Back to Recorded Courses</button><h2 className="fw-bold mb-1">Manage Recorded Course</h2></div>{error&&<div className="alert alert-danger">{error}</div>}
 <div className="card border-0 shadow-sm mb-4"><div className="card-body"><h5 className="fw-bold mb-3">Course Details</h5><form onSubmit={update}><div className="row g-3"><div className="col-md-6"><label className="form-label">Title</label><input required className="form-control" value={course.title} onChange={e=>setCourse({...course,title:e.target.value})}/></div><div className="col-md-3"><label className="form-label">Price (₹)</label><input type="number" min="0" step=".01" required className="form-control" value={course.price} onChange={e=>setCourse({...course,price:e.target.value})}/></div><div className="col-md-3"><label className="form-label">Access Days</label><input type="number" min="1" required className="form-control" value={course.access_duration_days} onChange={e=>setCourse({...course,access_duration_days:e.target.value})}/></div><div className="col-12"><label className="form-label">Description</label><textarea rows={3} className="form-control" value={course.description} onChange={e=>setCourse({...course,description:e.target.value})}/></div><div className="col-12 d-flex justify-content-between"><div className="form-check"><input type="checkbox" className="form-check-input" checked={course.is_active} onChange={e=>setCourse({...course,is_active:e.target.checked})}/><label className="form-check-label">Active</label></div><button className="btn btn-primary">Save Changes</button></div></div></form></div></div>
 <div className="card border-0 shadow-sm mb-4"><div className="card-body"><h5 className="fw-bold mb-3">Upload Lesson</h5><form onSubmit={upload}><div className="row g-3"><div className="col-md-6"><label className="form-label">Lesson Title</label><input required className="form-control" value={lesson.title} onChange={e=>setLesson({...lesson,title:e.target.value})}/></div><div className="col-md-2"><label className="form-label">Position</label><input required min="1" type="number" className="form-control" value={lesson.position} onChange={e=>setLesson({...lesson,position:e.target.value})}/></div><div className="col-md-4"><label className="form-label">Video</label><input required accept=".mp4,.webm,.mov,video/*" type="file" className="form-control" onChange={e=>setLesson({...lesson,video:e.target.files?.[0]||null})}/></div><div className="col-12"><label className="form-label">Description</label><textarea className="form-control" value={lesson.description} onChange={e=>setLesson({...lesson,description:e.target.value})}/></div><div className="col-12 text-end"><button className="btn btn-success">Upload Lesson</button></div></div></form></div></div>
 <div className="card border-0 shadow-sm"><div className="card-body border-bottom"><h5 className="fw-bold mb-0">Lessons</h5></div>{!course.lessons?.length?<div className="p-4 text-muted">No lessons uploaded yet.</div>:<div className="table-responsive"><table className="table align-middle mb-0"><thead><tr><th>#</th><th>Lesson</th><th>Status</th></tr></thead><tbody>{course.lessons.map((l:any)=><tr key={l.id}><td>{l.position}</td><td><div className="fw-semibold">{l.title}</div><small className="text-muted">{l.description||"-"}</small></td><td><span className={`badge ${l.is_active?"bg-success":"bg-secondary"}`}>{l.is_active?"Active":"Inactive"}</span></td></tr>)}</tbody></table></div>}</div>
 </div></div></main></div>
}