"use client";

import {useEffect,useRef,useState} from "react";
import {useParams,useRouter} from "next/navigation";
import StudentSidebar from "@/components/student/studentsidebar";
import StudentTopbar from "@/components/student/studentTopbar";
import StudentFeatureRestricted, { isClassFeatureRestricted } from "@/components/student/StudentFeatureRestricted";
import "../../dashboard/dashboard.css";

const API_BASE=process.env.NEXT_PUBLIC_API_BASE_URL;
type Course={id:number;title:string;description:string;access_expires_at:string|null;lessons:{id:number;title:string;description:string;position:number}[]};

export default function PurchasedCoursePage(){
 const params=useParams();const router=useRouter();const courseId=params.id as string;const [student,setStudent]=useState<any>({});const [course,setCourse]=useState<Course|null>(null);const [selected,setSelected]=useState<number|null>(null);const [videoUrl,setVideoUrl]=useState("");const [loading,setLoading]=useState(true);const [videoLoading,setVideoLoading]=useState(false);const [error,setError]=useState("");const currentUrl=useRef("");
 useEffect(()=>{try{setStudent(JSON.parse(localStorage.getItem("student_user")||"{}"))}catch{};const token=localStorage.getItem("student_access_token");if(!token){router.replace("/student/login");return}fetch(API_BASE+"/api/recorded-courses/student/my-courses/"+courseId+"/",{headers:{Authorization:"Bearer "+token}}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.detail||"Unable to open course.");return j.course}).then(c=>{setCourse(c);if(c.lessons?.length)setSelected(c.lessons[0].id)}).catch(e=>setError(e.message)).finally(()=>setLoading(false));return()=>{if(currentUrl.current)URL.revokeObjectURL(currentUrl.current)}},[courseId,router]);
 useEffect(()=>{if(!selected)return;const token=localStorage.getItem("student_access_token");if(!token)return;setVideoLoading(true);setError("");fetch(API_BASE+"/api/recorded-courses/student/lessons/"+selected+"/play/",{headers:{Authorization:"Bearer "+token}}).then(async r=>{if(!r.ok){let msg="Unable to play this lesson.";try{const j=await r.json();msg=j.detail||msg}catch{}throw new Error(msg)}return r.blob()}).then(blob=>{if(currentUrl.current)URL.revokeObjectURL(currentUrl.current);const u=URL.createObjectURL(blob);currentUrl.current=u;setVideoUrl(u)}).catch(e=>{setVideoUrl("");setError(e.message)}).finally(()=>setVideoLoading(false))},[selected]);
 const lesson=course?.lessons.find(l=>l.id===selected);
 return <div className="student-dashboard"><StudentSidebar/><main className="student-dashboard-main"><StudentTopbar name={student.name||student.username||"Student"} organization={student.organization||""}/><div className="student-dashboard-content"><div className="container-fluid">
 {isClassFeatureRestricted(error)?<StudentFeatureRestricted featureName="Recorded Courses" />:loading?<div className="dashboard-panel"><div className="empty-state">Loading purchased course...</div></div>:error&&!course?<div className="alert alert-danger">{error}</div>:course&&<><div className="d-flex justify-content-between align-items-start flex-wrap gap-2 mb-4"><div><h2 className="fw-bold mb-1">{course.title}</h2><p className="text-muted mb-0">{course.description}</p></div>{course.access_expires_at&&<span className="badge bg-success fs-6">Access until {new Date(course.access_expires_at).toLocaleDateString()}</span>}</div>
 {error&&<div className="alert alert-danger">{error}</div>}<div className="row g-4"><div className="col-lg-8"><div className="card border-0 shadow-sm"><div className="card-body"><h5 className="fw-bold mb-3">{lesson?.title||"Select a lesson"}</h5>{videoLoading?<div className="ratio ratio-16x9 bg-dark d-flex align-items-center justify-content-center"><div className="text-white text-center pt-5">Loading secure video...</div></div>:videoUrl?<video key={videoUrl} className="w-100 rounded bg-dark" controls controlsList="nodownload" disablePictureInPicture onContextMenu={e=>e.preventDefault()} src={videoUrl}/>:<div className="ratio ratio-16x9 bg-dark text-white"><div className="d-flex align-items-center justify-content-center">Video unavailable</div></div>}{lesson?.description&&<p className="mt-3 mb-0 text-muted">{lesson.description}</p>}</div></div></div>
 <div className="col-lg-4"><div className="card border-0 shadow-sm"><div className="card-header bg-white"><h5 className="mb-0 fw-bold">Lessons</h5></div><div className="list-group list-group-flush">{course.lessons.map((l,i)=><button key={l.id} className={"list-group-item list-group-item-action text-start "+(selected===l.id?"active":"")} onClick={()=>setSelected(l.id)}><div className="fw-semibold">{i+1}. {l.title}</div>{l.description&&<small className={selected===l.id?"text-white":"text-muted"}>{l.description}</small>}</button>)}</div></div></div></div></>}
 </div></div></main></div>
}